export const ACCOUNT_KEY_SNIPPET_COUNT = 5;
export const ACCOUNT_KEY_SNIPPET_LENGTH = 6;

export const MAX_ACCOUNT_KEY_SNIPPET_LENGTH = ACCOUNT_KEY_SNIPPET_COUNT * ACCOUNT_KEY_SNIPPET_LENGTH;

export const ACCOUNT_VERSION_LENGTH = 2;

export const ACCOUNT_VERSION_REGEX = /^[a-zA-Z0-9]{2}$/;
export const ACCOUNT_SECRET_REGEX = /^[a-zA-Z0-9]+$/;
